openapi: 3.0.0
info:
  title: API для автентифікації користувачів у агромаркетплейсі "Grassy"
  version: 1.0.0
  description: API для автентифікації користувачів (реєстрація та логінування)
servers:
  - url: http://localhost:3000/api/v1
    description: Локальний сервер для розробки
paths:
  /auth/register:
    post:
      summary: Реєстрація нового користувача
      description: Створення нового користувача в системі та повертає access/refresh токени
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: Успішна реєстрація
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseDto'
        '409':
          description: Користувач з такою електронною скринькою вже існує
        '500':
          description: Внутрішня помилка сервера
  /auth/login:
    post:
      summary: Логін користувача
      description: Виконання автентифікації користувача за адресою електронної скриньки та паролелем та повернення access та refreh токенів у відповідь
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: Успішне логінування
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseDto'
        '401':
          description: Невірний email або пароль
        '500':
          description: Внутрішня помилка сервера
components:
  schemas:
    RegisterDto:
      type: object
      properties:
        email:
          type: string
          format: email
          example: evgeniaivanenko@gmail.com
        password:
          type: string
          format: password
          example: &N9?Sxn:HrNCo,L~U[DlBfqg=[)3_–re4Xx
        firstName:
          type: string
          example: Evgenia
        lastName:
          type: string
          example: Petrenko
      required:
        - email
        - password
    LoginDto:
      type: object
      properties:
        email:
          type: string
          format: email
          example: evgeniaivanenko@example.com
        password:
          type: string
          format: password
          example: &N9?Sxn:HrNCo,L~U[DlBfqg=[)3_–re4Xx
      required:
        - email
        - password
    AuthResponseDto:
      type: object
      properties:
        accessToken:
          type: string
          example: a8189df05f42773413e9841f4a272392af6bc84d2e86ff846540c262d9613c0ca6fbf72e2be3e1b4761a0430afbe8b2a4d80986437d6ad551eef8d27a7be4856
        refreshToken:
          type: string
          example: 86bf87475506ddb02c2a4f75a1429a0f6385a8756c1b723347ad0986b74a4dcd88433a35f98b1de28e7b3ea1aee7efdbf47e139422800d8d5199506c4d769af8873c8631bc7b2eb55165117e37ce9d4f0d74af68f4698b38ea2968701928310ce1378bb6656054cd6fb86859ffb721ac6861de171658c2faea91572f
        user:
          type: object
          properties:
            id:
              type: string
              example: 123e4567-e89b-12d3-a456-426614174000
            email:
              type: string
              format: email
              example: evgeniaivanenko@gmail.com
            firstName:
              type: string
              example: Євгенія
            lastName:
              type: string
              example: Петренко
            role:
              type: string
              enum: [USER, SELLER, DRIVER, CONTROLLER]
              example: USER